<application>
  <component name="AppStorage">
    <histories>
      <item value="话题" />
      <item value="exception" />
      <item value="parsing" />
      <item value="parsing_exception" />
      <item value="mapper" />
      <item value="mapper_parsing_exception" />
      <item value="http://media.china.com.cn" />
      <item value="elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'failed to parse [web_type]') " />
      <item value="RuntimeError: dictionary changed size during iteration" />
      <item value="ValueError: Cannot assign &quot;'0'&quot;: &quot;DataClassTwo.ParentId&quot; must be a &quot;DataClassOne&quot; instance." />
      <item value="Look up an object with the given kwargs, updating one with defaults if it exists, otherwise create a new one. Return a tuple (object, created), where created is a boolean specifying whether an object was created." />
      <item value="Look up an object with the given kwargs, creating one if necessary. Return a tuple of (object, created), where created is a boolean specifying whether an object was created." />
      <item value="pykafka.exceptions.UnknownTopicOrPartition: Failed to auto-create topic 'b'sc_kafka_content''" />
      <item value="DOWNLOAD DELAY" />
      <item value="already started" />
      <item value="Look for an application configuration to attach the model to." />
      <item value="django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings. " />
      <item value="django.db.utils.OperationalError: (1045, &quot;Access denied for user 'zkr_cj'@'192.168.120.47' (using password: YES)&quot;) " />
      <item value="ScopeManagement.OneReport.LevelId: (fields.E305) Reverse query name for 'OneReport.LevelId' clashes with reverse query name for 'KeyWords.LevelId'.         HINT: Add or change a related_name argument to the definition for 'OneReport.LevelId' or 'KeyWords.LevelId'. " />
      <item value="黑名单" />
      <item value="latency" />
      <item value="latency " />
      <item value="related" />
      <item value="调度" />
      <item value="Cro Cycle" />
      <item value="when" />
      <item value="MIDNIGHT" />
      <item value="切割日志" />
      <item value="compute Rollover" />
      <item value="Work out the rollover time based on the specified time." />
      <item value="Determine if rollover should occur. record is not used, as we are just comparing times, but it is needed so the method signatures are the same" />
      <item value="Monitor" />
      <item value="关注" />
      <item value="attetion" />
      <item value="attetions" />
      <item value="上报" />
      <item value="low" />
      <item value="middle" />
      <item value="midele" />
      <item value="account" />
      <item value="账号" />
      <item value="ContentCount" />
      <item value="contentcount" />
      <item value="content" />
      <item value="contentscount" />
      <item value="elasticsearch.exceptions.TransportError: TransportError(503, '') Traceback (most recent call last):   File &quot;NewsInfo.py&quot;, line 99, in &lt;module&gt;     getInfo.run()   File &quot;NewsInfo.py&quot;, line 53, in run     boo = self.es.exists(&quot;xw_info&quot;, &quot;sino&quot;, _id)   File &quot;/usr/local/lib/python3.5/site-packages/elasticsearch/client/utils.py&quot;, line 76, in _wrapped     return func(*args, params=params, **kwargs)   File &quot;/usr/local/lib/python3.5/site-packages/elasticsearch/client/__init__.py&quot;, line 338, in exists     doc_type, id), params=params)   File &quot;/usr/local/lib/python3.5/site-packages/elasticsearch/transport.py&quot;, line 314, in perform_request     status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)   File &quot;/usr/local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py&quot;, line 163, in perform_request     self._raise_error(response.status, raw_data)   File &quot;/usr/local/lib/python3.5/site-packages/elasticsearch/connection/base.py&quot;, line 125, in _raise_error     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info) elasticsearch.exceptions.TransportError: TransportError(503, '')" />
      <item value="identify" />
      <item value="distinguish" />
      <item value="discern" />
      <item value="识别" />
    </histories>
    <option name="languageScores">
      <map>
        <entry key="CHINESE" value="159" />
        <entry key="ENGLISH" value="160" />
        <entry key="GERMAN" value="1" />
        <entry key="FRENCH" value="1" />
        <entry key="HAITIAN_CREOLE" value="3" />
        <entry key="ROMANIAN" value="2" />
        <entry key="SWEDISH" value="4" />
        <entry key="TELUGU" value="1" />
        <entry key="TURKISH" value="1" />
        <entry key="HINDI" value="2" />
      </map>
    </option>
  </component>
</application>